---
- hosts: all
  sudo: yes
  tasks:
    - name: install java
      apt: name=openjdk-7-jre-headless state=present update_cache=yes

    - name: add the logstash key
      apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

    - name: add the logstash deb package
      apt_repository: repo='{{ item }}' state=present
      with_items: 
        - deb http://packages.elasticsearch.org/elasticsearch/1.1/debian stable main
        - deb http://packages.elasticsearch.org/logstash/1.4/debian stable main
  
    - name: install elastic search
      apt: name=elasticsearch=1.1.1 state=present  

    - name: install logstash
      apt: name=logstash=1.4.2-1-2c0f5a1 state=present

    - name: copy over kibanna
      unarchive: src=kibana-3.1.0.tar.gz dest=/var/www/kibana3/

    - name: install nginx
      apt: name=nginx state=present

    - name: copy over the nginx conf
      copy: src=nginx.conf dest=/etc/nginx/sites-available/default

    - name: restart nginx
      service: name=nginx state=restarted 
