---
- hosts: all
  sudo: yes
  roles:
    - elasticsearch
  tasks:
    - name: install java
      apt: name=openjdk-7-jre-headless state=present update_cache=yes

    - name: add the logstash key
      apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

    - name: add the logstash deb package
      apt_repository: repo='{{ item }}' state=present
      with_items: 
        - deb http://packages.elasticsearch.org/logstash/1.4/debian stable main
        - deb http://packages.elasticsearch.org/logstashforwarder/debian stable main
  
    - name: install logstash
      apt: name=logstash=1.4.2-1-2c0f5a1 state=present

    - name: copy over kibanna
      unarchive: src=kibana-3.1.0.tar.gz dest=/var/www/

    - name: install nginx
      apt: name=nginx state=present

    - name: copy over the nginx conf
      copy: src=nginx.conf dest=/etc/nginx/sites-available/default

    - name: restart nginx
      service: name=nginx state=restarted 
   
    - name: copy over the logstash config files
      copy: src={{ item }} dest=/etc/logstash/conf.d/
      with_items:
        - 01-lumberjack-input.conf
        - 10-syslog.conf
        - 30-lumberjack-output.conf
 
    - name: install the forwarder for localhost
      apt: name=logstash-forwarder state=present

    - name: copy over the logstash forwarder config
      copy: src=logstash-forwarder dest=/etc/

    - name: make the directories for the crt
      file: path={{ item }} state=directory
      with_items:
        - /etc/pki/tls/certs
        - /etc/pki/tls/private

    - name: copy the crt to logstash box
      copy: src=logstash-forwarder.crt dest=/etc/pki/tls/certs/

    - name: copy the key to logstash box
      copy: src=logstash-forwarder.key dest=/etc/pki/tls/private/
   
    - name: start logstash
      service: name=logstash state=restarted  
    
    - name: restart logstash forwarder
      service: name=logstash-forwarder state=restarted 
