- name: install java
  apt: name=openjdk-7-jre-headless state=present update_cache=yes

- name: add the logstash key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add the logstash deb package
  apt_repository: repo='{{ item }}' state=present
  with_items:
    - deb http://packages.elasticsearch.org/elasticsearch/1.1/debian stable main

- name: install elastic search
  apt: name=elasticsearch=1.1.1 state=present

- name: start elastic
  service: name=elasticsearch state=started
